In [48]:
import pandas as pd 
import plotly.figure_factory as ff
import plotly.express as px

# combine csvs into one dataframe from the dataset folder 
df09to19 = pd.read_csv('./Dataset/2009-2019.csv')
df20p1 = pd.read_csv('./Dataset/2020p1.csv')
df20p2 = pd.read_csv('./Dataset/2020p2.csv')
df21 = pd.read_csv('./Dataset/2021.csv')
df22 = pd.read_csv('./Dataset/2022.csv')


df = pd.concat([df09to19, df20p1, df20p2, df21, df22])

df = df[['Occur Date', 'Occur Time', 'Possible Date', 'Possible Time', 'Location', 'UCR Literal','Neighborhood', 'Latitude', 'Longitude', ]]


df.isna().sum()

X:\Users\hakan\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

Occur Date       47830
Occur Time       47830
Possible Date    47848
Possible Time    47849
Location         47832
UCR Literal      47830
Neighborhood     60193
Latitude         47830
Longitude        47830
dtype: int64

In [49]:
df.head()
df.dropna(subset=['Occur Date'], inplace=True)

In [50]:
df

,Occur Date,Occur Time,Possible Date,Possible Time,Location,UCR Literal,Neighborhood,Latitude,Longitude
0,1/1/2009,11:45,1/1/2009,11:48,2841 GREENBRIAR PKWY,LARCENY-NON VEHICLE,Greenbriar,33.68845,-84.49328
1,1/1/2009,13:30,1/1/2009,13:30,12 BROAD ST SW,LARCENY-NON VEHICLE,Downtown,33.75320,-84.39201
2,1/1/2009,15:00,1/1/2009,15:20,3500 MARTIN L KING JR DR SW,LARCENY-NON VEHICLE,Adamsville,33.75735,-84.50282
3,1/1/2009,14:50,1/1/2009,15:10,3393 PEACHTREE RD NE,LARCENY-NON VEHICLE,Lenox,33.84676,-84.36212
4,1/1/2009,16:00,1/1/2009,17:00,2841 GREENBRIAR PKWY SW,LARCENY-NON VEHICLE,Greenbriar,33.68677,-84.49773
...,...,...,...,...,...,...,...,...,...
342909,12/31/2019,20:30,12/31/2019,20:34,1385 SHARON ST NW,AGG ASSAULT,Hunter Hills,33.75486,-84.43287
342910,12/31/2019,04:32,12/31/2019,04:32,262 PHARR RD NE,AGG ASSAULT,Buckhead Village,33.83732,-84.37860
342911,12/31/2019,09:20,12/31/2019,09:40,689 CASCADE AVE SW,AGG ASSAULT,Westview,33.73636,-84.43680
342912,12/31/2019,18:53,12/31/2019,19:00,763 CASCADE AVE SW,AGG ASSAULT,Westview,33.73483,-84.43750
342913,12/31/2019,20:45,12/31/2019,20:55,237 PEYTON PL SW,AGG ASSAULT,Cascade Avenue/Road,33.72518,-84.45013

In [51]:
# Report Date to datetime
# Occur Date	Occur Time combined as date and time 
# Possible Date	Possible Time combined as date and time 


# df['Occur Time'] = df['Occur Time'].astype(str)

# # if the length is less than 4, then it is a single digit number, so add a 0 in front of it
# df['Occur Time'] = df['Occur Time'].apply(lambda x: '0' + x if len(x) < 4 else x)
    
# df['Occur Time'] = df['Occur Time'].apply(lambda x: str(
#     x)[0:2]) + ':' + df['Occur Time'].apply(lambda x: str(x)[2:4])






# #turn possibletime into time
# df['Possible Time'] = df['Possible Time'].astype(str)
# df['Possible Time'] = df['Possible Time'].apply(
#     lambda x: '0' + x if len(x) < 4 else x)

# df['Possible Time'] = df['Possible Time'].apply(lambda x: str(
#     x)[0:2]) + ':' + df['Possible Time'].apply(lambda x: str(x)[2:4])




df.columns = df.columns.str.replace('Occur Date', 'occur_date')
df.columns = df.columns.str.replace('Occur Time', 'occur_time')
df.columns = df.columns.str.replace('Possible Date', 'possible_date')
df.columns = df.columns.str.replace('Possible Time', 'possible_time')
df.columns = df.columns.str.replace('Location', 'location')
df.columns = df.columns.str.replace('UCR Literal', 'ucr_literal')
df.columns = df.columns.str.replace('Neighborhood', 'neighborhood')
df.columns = df.columns.str.replace('Latitude', 'latitude')
df.columns = df.columns.str.replace('Longitude', 'longitude')


# df.to_csv('./Dataset/df.csv')
df['occur_time']

0         11:45
1         13:30
2         15:00
3         14:50
4         16:00
          ...
342909    20:30
342910    04:32
342911    09:20
342912    18:53
342913    20:45
Name: occur_time, Length: 342914, dtype: object

In [56]:
#convert to string first 
 

#convert to datetime 
df['occur_datet_new'] = df['occur_date'] + ' ' + df['occur_time']
df['occur_datet_new'] = pd.to_datetime(df['occur_datet_new'])


df['occur_datet_new']

0        2009-01-01 11:45:00
1        2009-01-01 13:30:00
2        2009-01-01 15:00:00
3        2009-01-01 14:50:00
4        2009-01-01 16:00:00
                 ...
342909   2019-12-31 20:30:00
342910   2019-12-31 04:32:00
342911   2019-12-31 09:20:00
342912   2019-12-31 18:53:00
342913   2019-12-31 20:45:00
Name: occur_datet_new, Length: 342914, dtype: datetime64[ns]